### PR TITLE
Release held requests sequentially

### PR DESCRIPTION
**Pull request by mxstbr**
This makes it so that held requests are released sequentially, rather than in parallel. This is important for our chat app as messages need to arrive at the server in-order.

I understand if this isn't necessary for your app/use case, maybe this should be an option instead?

> Note: I have 0 experience with observables, so just let me know else to make this happen if there's a better way. I also didn't manage to write tests since I don't understand the test utils, any help there would be appreciated.

### CODE REVIEW

**Comment by mxstbr** [comment]
This only fails due to #6, but works locally in my app as expected!

**Comment by mxstbr** [comment]
There's an edge case that I hadn't considered: What if, while the queued requests are executed sequentially, another request comes in?

Then the request would fire in the middle of the others, even though it would be at the end.

I think I might need to refactor this to always pass requests through the `replay` method, and then pause replaying when offline or something?

**Comment by helfer** [comment]
> There's an edge case that I hadn't considered: What if, while the queued requests are executed sequentially, another request comes in?
> Then the request would fire in the middle of the others, even though it would be at the end.

Yeah, I actually have a very similar use-case (offline creation & editing of notes), so I built another separate link for it for the reason you mentioned above. I called it [apollo-link-serialize](https://github.com/helfer/apollo-link-serialize).

Because there's also no guarantee that the network delivers requests in order (especially for mobile), apollo-link-serialize actually waits until all previous requests with the same serialization key have either succeeded or failed before sending the next request. An alternative would be to use websockets instead, which guarantee the order of delivery. If that's not an option, and if waiting for previous requests to succeed would be too slow, then I think the only option is to somehow guarantee the order on the server.

**Comment by mxstbr** [comment]
Ohh, apollo-link-serialize looks awesome! 😍 Can I combine that link with this one and the retry link?

**Comment by helfer** [comment]
You certainly can! Here's an [example](https://github.com/helfer/zetteli/blob/master/client/src/services/GraphQLClient.ts#L76-L95) of how I combined them for my app.

**Pull request closed without merging**
