### PR TITLE
Allow persistence and filtering

### PR DESCRIPTION
**Pull request by wtrocki**
## Motivation

Allow queue persistence and filtering. 
Support use cases when:
- Queue should only process mutations
- Page was refreshed and queued elements will be removed

## Implementation

Using interface that can match local storage or any other platform storage
No extra packages
No change in current behavior (additional object passed to add extra storage and filter )

# TODO

More unit tests

### CODE REVIEW

**Comment by wtrocki** [comment]
Thabks for heads up. I haven't checked React Native use case yet. I think I need to improve this PR by:
- Adding debug logging
- Adding apollo client to reshedule operations (rebuild observer chain after restart)
- Test both React Native and Browser use cases

**Comment by wtrocki** [comment]
I have done some experiments and I think that this PR will change behavior of the package to such extend that it will need to be renamed to not cause issues with current implementations

If you looking for already functional example of the queue with offline support see https://github.com/aerogear/offline-conflict-strategies/tree/master/web/src/sdk/mutations

Just copy this two classes into your app
I'm going to port that to separate apollo-link-offline-queue

**Comment by helfer** [comment]
Hi @wtrocki, first off, thanks a lot for the PR and my apologies for not responding sooner.

I agree that this is a fairly significant change that might be better off in a separate package.

Alternatively to this implementation for persisting the queue, how about adding public functions that allow getting and setting the content of the queue? That way, any necessary persistence/hydration for orderly shutdowns can be done by an external function.

If the goal is to provide persistence + replay even in the case of unplanned shutdowns, then I think that concern would be best solved in a separate link which persists operations while they're pending, and replays all operations on startup. However, like I commented in another thread, this will not give you the kind of offline support you may expect when using it with Apollo Client, because it's not enough for the link to replay the requests, the store also needs to know about pending operations if their results should be optimistically showed to the user.

**Comment by wtrocki** [comment]
Fully agree. Closing PR.

**Pull request closed without merging**
